### ISSUE TITLE
color of disabled elements

### ISSUE THREAD

**Issue by PPPCR** [arsava/dokuwiki-template-vector#46]
Disabled elements use neutrale text color ``` __text_neu__``` as defined in style.ini, which is ```"#000"```. This value doesn't differ from default text color ``` __text__```, which makes it hard / impossible do recognize them as being disabled.

Possible solution: use another color, e.g. #999

In static/css/screen.css the following is given:
```css
div.dokuwiki textarea.edit[disabled],
div.dokuwiki textarea.edit[readonly],
div.dokuwiki input.edit[disabled],
div.dokuwiki input.edit[readonly],
div.dokuwiki input.button[disabled],
div.dokuwiki select.edit[disabled] {
  background-color: __background_neu__!important;
  color: __text_neu__!important;
  font-weight: normal;
}
```
